### Open Flights Data Wrangling

To practice, you are going to wrangle data from OpenFlights.  You can read about it here: 

http://openflights.org/data.html

This includes three main files, one for each airport, one for each airline, and one for each route.  They can be merged or joined with the appropriate fields.  I have modified the files slightly to include a header row in the .dat files, which makes it a bit easier for you.  

You are required to work through the problems below.  This may take some time.  Be persistent, and ask questions or seek help as needed.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# These files use \N as a missing value indicator.  When reading the CSVs, we will tell
# it to use that value as missing or NA.  The double backslash is required because
# otherwise it will interpret \N as a carriage return. 

# Read in the airports data.
airports = pd.read_csv("data/airports.dat", header=None, na_values='\\N')
airports.columns = ["id", "name", "city", "country", "iata", "icao", "latitude", "longitude", "altitude","timezone", "dst", "tz", "type", "source"]

# Read in the airlines data.
airlines = pd.read_csv("data/airlines.dat", header=None, na_values='\\N')
airlines.columns = ["id", "name", "alias", "iata", "icao", "callsign", "country", "active"]

# Read in the routes data.
routes = pd.read_csv("data/routes.dat", header=None, na_values='\\N')
routes.columns = ["airline", "airline_id", "source", "source_id", "dest", "dest_id", "codeshare", "stops", "equipment"]

1) Start by seeing what's in the data.  What columns are there?  What data types are the columns?  

Remember, 'object' means it is a string, while the numerical values can be floats or ints.  Sometimes you will have problems if it reads numeric data in as strings.  If that happens, you can use the function .astype() to convert it.  Look it up in the pandas API to get more details

In [3]:
print(airports)

         id                                         name                city  \
0         1                               Goroka Airport              Goroka
1         2                               Madang Airport              Madang
2         3                 Mount Hagen Kagamuga Airport         Mount Hagen
3         4                               Nadzab Airport              Nadzab
4         5  Port Moresby Jacksons International Airport        Port Moresby
5         6                  Wewak International Airport               Wewak
6         7                           Narsarsuaq Airport        Narssarssuaq
7         8                      Godthaab / Nuuk Airport            Godthaab
8         9                        Kangerlussuaq Airport         Sondrestrom
9        10                               Thule Air Base               Thule
10       11                             Akureyri Airport            Akureyri
11       12                          Egilsstaðir Airport         Egilsstadir
12       13                         Hornafjörður Airport                Hofn
13       14                              Húsavík Airport             Husavik
14       15                           Ísafjörður Airport          Isafjordur
15       16               Keflavik International Airport            Keflavik
16       17                       Patreksfjörður Airport      Patreksfjordur
17       18                            Reykjavik Airport           Reykjavik
18       19                         Siglufjörður Airport        Siglufjordur
19       20                       Vestmannaeyjar Airport      Vestmannaeyjar
20       21                      Sault Ste Marie Airport  Sault Sainte Marie
21       22               Winnipeg / St. Andrews Airport            Winnipeg
22       23            Halifax / CFB Shearwater Heliport             Halifax
23       24                          St. Anthony Airport         St. Anthony
24       25                  Tofino / Long Beach Airport              Tofino
25       26                             Kugaaruk Airport           Pelly Bay
26       27                          Baie Comeau Airport         Baie Comeau
27       28                               CFB Bagotville          Bagotville
28       29                           Baker Lake Airport          Baker Lake
29       30                       Campbell River Airport      Campbell River
...     ...                                          ...                 ...
7154  12028                               Kerang Airport                 NaN
7155  12029                              Kempsey Airport                 NaN
7156  12030                             Kingaroy Airport                 NaN
7157  12031                       Latrobe Valley Airport             Morwell
7158  12032                              Mareeba Airport                 NaN
7159  12033                              Ngukurr Airport                 NaN
7160  12034                            Narromine Airport                 NaN
7161  12035                           Port Pirie Airport                 NaN
7162  12036                             Smithton Airport                 NaN
7163  12037                            Snake Bay Airport                 NaN
7164  12038                              Stawell Airport                 NaN
7165  12039                           Tibooburra Airport                 NaN
7166  12040                                Tumut Airport                 NaN
7167  12041                           Wangaratta Airport                 NaN
7168  12042                        Warracknabeal Airport                 NaN
7169  12043                               Warren Airport                 NaN
7170  12044                            West Sale Airport                Sale
7171  12045                         West Wyalong Airport        West Wyalong
7172  12046                                Young Airport                 NaN
7173  12047                        Guangzhou MR Air Base            Guanghua
7174  12048                    Shiyan Wudangshan Airport              Shiyan
7175  12049                             Sunchon Air Base             Sunchon
7176  12050                             Huatugou Airport             Mengnai
7177  12051                           Baruun Urt Airport                 NaN
7178  12052                               Bengbu Airport              Bengbu
7179  12053                               Rugao Air Base               Rugao
7180  12054                                Wuhu Air Base                Wuhu
7181  12055                             Shanshan Airport            Shanshan
7182  12056                        Yingkou Lanqi Airport             Yingkou
7183  12057                      Shenyang Dongta Airport            Shenyang

               country iata  icao   latitude   longitude  altitude  timezone  \
0     Papua New Guinea  GKA  AYGA  -6.081690  145.391998      5282      10.0
1     Papua New Guinea  MAG  AYMD  -5.207080  145.789001        20      10.0
2     Papua New Guinea  HGU  AYMH  -5.826790  144.296005      5388      10.0
3     Papua New Guinea  LAE  AYNZ  -6.569803  146.725977       239      10.0
4     Papua New Guinea  POM  AYPY  -9.443380  147.220001       146      10.0
5     Papua New Guinea  WWK  AYWK  -3.583830  143.669006        19      10.0
6            Greenland  UAK  BGBW  61.160500  -45.425999       112      -3.0
7            Greenland  GOH  BGGH  64.190903  -51.678101       283      -3.0
8            Greenland  SFJ  BGSF  67.012222  -50.711603       165      -3.0
9            Greenland  THU  BGTL  76.531197  -68.703201       251      -4.0
10             Iceland  AEY  BIAR  65.660004  -18.072701         6       0.0
11             Iceland  EGS  BIEG  65.283302  -14.401400        76       0.0
12             Iceland  HFN  BIHN  64.295601  -15.227200        24       0.0
13             Iceland  HZK  BIHU  65.952301  -17.426001        48       0.0
14             Iceland  IFJ  BIIS  66.058098  -23.135300         8       0.0
15             Iceland  KEF  BIKF  63.985001  -22.605600       171       0.0
16             Iceland  PFJ  BIPA  65.555801  -23.965000        11       0.0
17             Iceland  RKV  BIRK  64.129997  -21.940599        48       0.0
18             Iceland  SIJ  BISI  66.133301  -18.916700        10       0.0
19             Iceland  VEY  BIVM  63.424301  -20.278900       326       0.0
20              Canada  YAM  CYAM  46.485001  -84.509399       630      -5.0
21              Canada  YAV  CYAV  50.056400  -97.032501       760      -6.0
22              Canada  YAW  CYAW  44.639702  -63.499401       144      -4.0
23              Canada  YAY  CYAY  51.391899  -56.083099       108      -3.5
24              Canada  YAZ  CYAZ  49.079833 -125.775583        80      -8.0
25              Canada  YBB  CYBB  68.534401  -89.808098        56      -7.0
26              Canada  YBC  CYBC  49.132500  -68.204399        71      -5.0
27              Canada  YBG  CYBG  48.330601  -70.996399       522      -5.0
28              Canada  YBK  CYBK  64.298897  -96.077797        59      -6.0
29              Canada  YBL  CYBL  49.950802 -125.271004       346      -8.0
...                ...  ...   ...        ...         ...       ...       ...
7154         Australia  KRA  YKER -35.751400  143.938995       254       NaN
7155         Australia  KPS  YKMP -31.074400  152.770004        54       NaN
7156         Australia  KGY  YKRY -26.580799  151.841003      1492       NaN
7157         Australia  TGN  YLTV -38.207199  146.470001       180       NaN
7158         Australia  MRG  YMBA -17.069201  145.419006      1560       NaN
7159         Australia  RPM  YNGU -14.722800  134.746994        45       NaN
7160         Australia  QRM  YNRM -32.214699  148.225006       782       NaN
7161         Australia  PPI  YPIR -33.238899  137.994995        40       NaN
7162         Australia  SIO  YSMI -40.834999  145.084000        31       NaN
7163         Australia  SNB  YSNB -11.422800  130.654007       173       NaN
7164         Australia  SWC  YSWL -37.071701  142.740997       807       NaN
7165         Australia  TYB  YTIB -29.451099  142.057999       584       NaN
7166         Australia  TUM  YTMU -35.262798  148.240997       878       NaN
7167         Australia  WGT  YWGT -36.415798  146.307007       504       NaN
7168         Australia  WKB  YWKB -36.321098  142.419006       397       NaN
7169         Australia  QRR  YWRN -31.733299  147.802994       669       NaN
7170         Australia  SXE  YWSL -38.090827  146.965335        72       NaN
7171         Australia  WWY  YWWL -33.937199  147.190994       859       NaN
7172         Australia  NGA  YYNG -34.255600  148.248001      1267       NaN
7173             China  LHK  ZHGH  32.389400  111.695000         0       NaN
7174             China  WDS  ZHSY  32.591667  110.907778         0       NaN
7175       North Korea  NaN  ZKSC  39.415699  125.894997       141       NaN
7176             China  HTT  ZLHX  38.201984   90.841495      2945       NaN
7177          Mongolia  UUN  ZMBU  46.660301  113.285004      3205       NaN
7178             China  BFU  ZSBB  32.847733  117.320244       100       NaN
7179             China  RUG  ZSRG  32.257885  120.501656         0       NaN
7180             China  WHU  ZSWU  31.390600  118.408997         0       NaN
7181             China  SXJ  ZWSS  42.911701   90.247498         0       NaN
7182             China  YKH  ZYYK  40.542524  122.358600         0       NaN
7183             China  NaN  ZYYY  41.784401  123.496002         0       NaN

      dst                    tz     type       source
0       U  Pacific/Port_Moresby  airport  OurAirports
1       U  Pacific/Port_Moresby  airport  OurAirports
2       U  Pacific/Port_Moresby  airport  OurAirports
3       U  Pacific/Port_Moresby  airport  OurAirports
4       U  Pacific/Port_Moresby  airport  OurAirports
5       U  Pacific/Port_Moresby  airport  OurAirports
6       E       America/Godthab  airport  OurAirports
7       E       America/Godthab  airport  OurAirports
8       E       America/Godthab  airport  OurAirports
9       E         America/Thule  airport  OurAirports
10      N    Atlantic/Reykjavik  airport  OurAirports
11      N    Atlantic/Reykjavik  airport  OurAirports
12      N    Atlantic/Reykjavik  airport  OurAirports
13      N    Atlantic/Reykjavik  airport  OurAirports
14      N    Atlantic/Reykjavik  airport  OurAirports
15      N    Atlantic/Reykjavik  airport  OurAirports
16      N    Atlantic/Reykjavik  airport  OurAirports
17      N    Atlantic/Reykjavik  airport  OurAirports
18      N    Atlantic/Reykjavik  airport  OurAirports
19      N    Atlantic/Reykjavik  airport  OurAirports
20      A       America/Toronto  airport  OurAirports
21      A      America/Winnipeg  airport  OurAirports
22      A       America/Halifax  airport  OurAirports
23      A      America/St_Johns  airport  OurAirports
24      A     America/Vancouver  airport  OurAirports
25      A      America/Edmonton  airport  OurAirports
26      A       America/Toronto  airport  OurAirports
27      A       America/Toronto  airport  OurAirports
28      A      America/Winnipeg  airport  OurAirports
29      A     America/Vancouver  airport  OurAirports
...   ...                   ...      ...          ...
7154  NaN                   NaN  airport  OurAirports
7155  NaN                   NaN  airport  OurAirports
7156  NaN                   NaN  airport  OurAirports
7157  NaN                   NaN  airport  OurAirports
7158  NaN                   NaN  airport  OurAirports
7159  NaN                   NaN  airport  OurAirports
7160  NaN                   NaN  airport  OurAirports
7161  NaN                   NaN  airport  OurAirports
7162  NaN                   NaN  airport  OurAirports
7163  NaN                   NaN  airport  OurAirports
7164  NaN                   NaN  airport  OurAirports
7165  NaN                   NaN  airport  OurAirports
7166  NaN                   NaN  airport  OurAirports
7167  NaN                   NaN  airport  OurAirports
7168  NaN                   NaN  airport  OurAirports
7169  NaN                   NaN  airport  OurAirports
7170  NaN                   NaN  airport  OurAirports
7171  NaN                   NaN  airport  OurAirports
7172  NaN                   NaN  airport  OurAirports
7173  NaN                   NaN  airport  OurAirports
7174  NaN                   NaN  airport  OurAirports
7175  NaN                   NaN  airport  OurAirports
7176  NaN                   NaN  airport  OurAirports
7177  NaN                   NaN  airport  OurAirports
7178  NaN                   NaN  airport  OurAirports
7179  NaN                   NaN  airport  OurAirports
7180  NaN                   NaN  airport  OurAirports
7181  NaN                   NaN  airport  OurAirports
7182  NaN                   NaN  airport  OurAirports
7183  NaN                   NaN  airport  OurAirports

[7184 rows x 14 columns]

In [4]:
print(airports.columns)

Index(['id', 'name', 'city', 'country', 'iata', 'icao', 'latitude',
       'longitude', 'altitude', 'timezone', 'dst', 'tz', 'type', 'source'],
      dtype='object')

In [5]:
print(airlines)

         id                                          name  \
0        -1                                       Unknown
1         1                                Private flight
2         2                                   135 Airways
3         3                                 1Time Airline
4         4  2 Sqn No 1 Elementary Flying Training School
5         5                               213 Flight Unit
6         6                 223 Flight Unit State Airline
7         7                             224th Flight Unit
8         8                                   247 Jet Ltd
9         9                                   3D Aviation
10       10                                   40-Mile Air
11       11                                        4D Air
12       12                        611897 Alberta Limited
13       13                              Ansett Australia
14       14                          Abacus International
15       15                               Abelag Aviation
16       16                                Army Air Corps
17       17                     Aero Aviation Centre Ltd.
18       18     Aero Servicios Ejecutivos Internacionales
19       19                                   Aero Biniza
20       20                                 Aero Albatros
21       21                                    Aigle Azur
22       22                                Aloha Airlines
23       23                             Alaska Island Air
24       24                             American Airlines
25       25               Aviation Management Corporation
26       26                       Atlantis Airlines (USA)
27       27                            Aerovista Airlines
28       28                               Asiana Airlines
29       29                               Askari Aviation
...     ...                                           ...
6132  20827                                    Fly France
6133  20875                                 Jota Aviation
6134  20881                                    Europe Jet
6135  20923                                        COBALT
6136  20931                      Southern Airways Express
6137  20961       Deutsche Luftverkehrsgesellschaft (DLT)
6138  20962                                   Orenburzhie
6139  20963                            Atlantic Air Cargo
6140  20976                          World Scale Airlines
6141  20978                                All America US
6142  20986   University of Birmingham Air Squadron (RAF)
6143  20991                                Choice Airways
6144  20994                                Aruba Airlines
6145  20995                                     BudgetAir
6146  20996                               Dynamic Airways
6147  21012                                       Fly One
6148  21021                                       Nordica
6149  21036                              Tez Jet Airlines
6150  21043                                      Kush Air
6151  21056                                         Dummy
6152  21124                                        ViaAir
6153  21131                              All America BOPY
6154  21179                              Thai Vietjet Air
6155  21181                              Air Andaman (2Y)
6156  21240                     TDA Toa Domestic Airlines
6157  21248                                   GX Airlines
6158  21251                        Lynx Aviation (L3/SSX)
6159  21268                               Jetgo Australia
6160  21270                                  Air Carnival
6161  21317                                 Svyaz Rossiya

                      alias iata icao         callsign               country  \
0                       NaN    -  NaN              NaN                   NaN
1                       NaN    -  NaN              NaN                   NaN
2                       NaN  NaN  GNL          GENERAL         United States
3                       NaN   1T  RNX          NEXTIME          South Africa
4                       NaN  NaN  WYT              NaN        United Kingdom
5                       NaN  NaN  TFU              NaN                Russia
6                       NaN  NaN  CHD   CHKALOVSK-AVIA                Russia
7                       NaN  NaN  TTF       CARGO UNIT                Russia
8                       NaN  NaN  TWF     CLOUD RUNNER        United Kingdom
9                       NaN  NaN  SEC          SECUREX         United States
10                      NaN   Q5  MLA         MILE-AIR         United States
11                      NaN  NaN  QRT          QUARTET              Thailand
12                      NaN  NaN  THD            DONUT                Canada
13                      NaN   AN  AAA           ANSETT             Australia
14                      NaN   1B  NaN              NaN             Singapore
15                      NaN   W9  AAB              ABG               Belgium
16                      NaN  NaN  AAC          ARMYAIR        United Kingdom
17                      NaN  NaN  AAD          SUNRISE                Canada
18                      NaN  NaN  SII           ASEISA                Mexico
19                      NaN  NaN  BZS           BINIZA                Mexico
20                      NaN  NaN  ABM  ALBATROS ESPANA                 Spain
21                      NaN   ZI  AAF       AIGLE AZUR                France
22                      NaN   AQ  AAH            ALOHA         United States
23                      NaN  NaN  AAK    ALASKA ISLAND         United States
24                      NaN   AA  AAL         AMERICAN         United States
25                      NaN  NaN  AAM          AM CORP         United States
26                      NaN  NaN  AAO     ATLANTIS AIR         United States
27                      NaN  NaN  AAP  AEROVISTA GROUP  United Arab Emirates
28                      NaN   OZ  AAR           ASIANA     Republic of Korea
29                      NaN   4K  AAS           AL-AAS              Pakistan
...                     ...  ...  ...              ...                   ...
6132             Fly France   FF  FRF              NaN                France
6133                    NaN  NaN  ENZ             ENZO        United Kingdom
6134             Europe Jet   EX  EU9              NaN                France
6135                 COBALT  NaN  FCB           COBALT                Cyprus
6136        Sun Air Express  NaN  LTD       LIGHTSPEED         United States
6137                    NaN   DW  DWD              NaN               Germany
6138                    NaN  NaN  ORG              NaN                Russia
6139                    NaN   K3  NaN              NaN         United States
6140            World Scale   W3  WSS              NaN         United States
6141         All America US   AG  SSA              NaN         United States
6142               8AEF RAF  NaN  UAY              UAY        United Kingdom
6143                    NaN  NaN  CSX              NaN         United States
6144                    NaN  NaN  ARU              NaN                 Aruba
6145              BudgetAir   1K  BG1              NaN               Germany
6146                    NaN  NaN  DYA              NaN         United States
6147                Fly One   F5  FI5              NaN               Moldova
6148                    NaN   EE  NaN            REVAL               Estonia
6149                    NaN  NaN  TEZ              NaN            Kyrgyzstan
6150                    NaN  NaN  KUH              NaN           South Sudan
6151                    NaN   0E  NaN              NaN                France
6152  Charter Air Transport  NaN  SRY         Stingray         United States
6153       All America BOPY   0P  PYB             BOPY              Paraguay
6154                    NaN  NaN  TVJ     THAIVIET JET              Thailand
6155                    NaN   2Y  AOW      AIR ANDAMAN              Thailand
6156                    TDA  NaN  TDA        Toa Domes                 Japan
6157                    NaN  NaN  CBG            SPRAY                 China
6158                    NaN  NaN  SSX           Shasta         United States
6159                    NaN   JG  NaN              NaN             Australia
6160                    NaN   2S  NaN              NaN                 India
6161      Russian Commuter    7R  SJM  RussianConnecty                Russia

     active
0         Y
1         Y
2         N
3         Y
4         N
5         N
6         N
7         N
8         N
9         N
10        Y
11        N
12        N
13        Y
14        Y
15        N
16        N
17        N
18        N
19        N
20        N
21        Y
22        Y
23        N
24        Y
25        N
26        N
27        N
28        Y
29        Y
...     ...
6132      Y
6133      Y
6134      Y
6135      Y
6136      Y
6137      N
6138      Y
6139      N
6140      Y
6141      Y
6142      Y
6143      Y
6144      Y
6145      Y
6146      Y
6147      Y
6148      Y
6149      Y
6150      Y
6151      N
6152      Y
6153      Y
6154      Y
6155      N
6156      N
6157      Y
6158      N
6159      Y
6160      Y
6161      Y

[6162 rows x 8 columns]

In [6]:
print(airlines.columns)

Index(['id', 'name', 'alias', 'iata', 'icao', 'callsign', 'country', 'active'], dtype='object')

In [7]:
print(routes)

      airline  airline_id source  source_id dest  dest_id codeshare  stops  \
0          2B       410.0    AER     2965.0  KZN   2990.0       NaN      0
1          2B       410.0    ASF     2966.0  KZN   2990.0       NaN      0
2          2B       410.0    ASF     2966.0  MRV   2962.0       NaN      0
3          2B       410.0    CEK     2968.0  KZN   2990.0       NaN      0
4          2B       410.0    CEK     2968.0  OVB   4078.0       NaN      0
5          2B       410.0    DME     4029.0  KZN   2990.0       NaN      0
6          2B       410.0    DME     4029.0  NBC   6969.0       NaN      0
7          2B       410.0    DME     4029.0  TGK      NaN       NaN      0
8          2B       410.0    DME     4029.0  UUA   6160.0       NaN      0
9          2B       410.0    EGO     6156.0  KGD   2952.0       NaN      0
10         2B       410.0    EGO     6156.0  KZN   2990.0       NaN      0
11         2B       410.0    GYD     2922.0  NBC   6969.0       NaN      0
12         2B       410.0    KGD     2952.0  EGO   6156.0       NaN      0
13         2B       410.0    KZN     2990.0  AER   2965.0       NaN      0
14         2B       410.0    KZN     2990.0  ASF   2966.0       NaN      0
15         2B       410.0    KZN     2990.0  CEK   2968.0       NaN      0
16         2B       410.0    KZN     2990.0  DME   4029.0       NaN      0
17         2B       410.0    KZN     2990.0  EGO   6156.0       NaN      0
18         2B       410.0    KZN     2990.0  LED   2948.0       NaN      0
19         2B       410.0    KZN     2990.0  SVX   2975.0       NaN      0
20         2B       410.0    LED     2948.0  KZN   2990.0       NaN      0
21         2B       410.0    LED     2948.0  NBC   6969.0       NaN      0
22         2B       410.0    LED     2948.0  UUA   6160.0       NaN      0
23         2B       410.0    MRV     2962.0  ASF   2966.0       NaN      0
24         2B       410.0    NBC     6969.0  DME   4029.0       NaN      0
25         2B       410.0    NBC     6969.0  GYD   2922.0       NaN      0
26         2B       410.0    NBC     6969.0  LED   2948.0       NaN      0
27         2B       410.0    NBC     6969.0  SVX   2975.0       NaN      0
28         2B       410.0    NJC     2972.0  SVX   2975.0       NaN      0
29         2B       410.0    NJC     2972.0  UUA   6160.0       NaN      0
...       ...         ...    ...        ...  ...      ...       ...    ...
67633      ZL      4178.0    SYD     3361.0  ABX   3333.0       NaN      0
67634      ZL      4178.0    SYD     3361.0  ARM   4062.0       NaN      0
67635      ZL      4178.0    SYD     3361.0  BHQ   6241.0       NaN      0
67636      ZL      4178.0    SYD     3361.0  BHS   6249.0       NaN      0
67637      ZL      4178.0    SYD     3361.0  BNK   4291.0       NaN      0
67638      ZL      4178.0    SYD     3361.0  DBO   3358.0       NaN      0
67639      ZL      4178.0    SYD     3361.0  GFF   6271.0       NaN      0
67640      ZL      4178.0    SYD     3361.0  LSY   6287.0       NaN      0
67641      ZL      4178.0    SYD     3361.0  MIM   6294.0       NaN      0
67642      ZL      4178.0    SYD     3361.0  MQL   6298.0       NaN      0
67643      ZL      4178.0    SYD     3361.0  MYA   6302.0       NaN      0
67644      ZL      4178.0    SYD     3361.0  NRA   6307.0       NaN      0
67645      ZL      4178.0    SYD     3361.0  NTL   4320.0       NaN      0
67646      ZL      4178.0    SYD     3361.0  OAG   6793.0       NaN      0
67647      ZL      4178.0    SYD     3361.0  PKE   6317.0       NaN      0
67648      ZL      4178.0    SYD     3361.0  TRO   6794.0       NaN      0
67649      ZL      4178.0    SYD     3361.0  WGA   3363.0       NaN      0
67650      ZL      4178.0    TRO     6794.0  GFN   6792.0       NaN      0
67651      ZL      4178.0    TRO     6794.0  SYD   3361.0       NaN      0
67652      ZL      4178.0    TSV     3330.0  ISA   3324.0       NaN      0
67653      ZL      4178.0    TSV     3330.0  WIN   6337.0       NaN      0
67654      ZL      4178.0    WGA     3363.0  MEL   3339.0       NaN      0
67655      ZL      4178.0    WGA     3363.0  SYD   3361.0       NaN      0
67656      ZL      4178.0    WIN     6337.0  LRE   6289.0       NaN      0
67657      ZL      4178.0    WIN     6337.0  TSV   3330.0       NaN      0
67658      ZL      4178.0    WYA     6334.0  ADL   3341.0       NaN      0
67659      ZM     19016.0    DME     4029.0  FRU   2912.0       NaN      0
67660      ZM     19016.0    FRU     2912.0  DME   4029.0       NaN      0
67661      ZM     19016.0    FRU     2912.0  OSS   2913.0       NaN      0
67662      ZM     19016.0    OSS     2913.0  FRU   2912.0       NaN      0

      equipment
0           CR2
1           CR2
2           CR2
3           CR2
4           CR2
5           CR2
6           CR2
7           CR2
8           CR2
9           CR2
10          CR2
11          CR2
12          CR2
13          CR2
14          CR2
15          CR2
16          CR2
17          CR2
18          CR2
19          CR2
20          CR2
21          CR2
22          CR2
23          CR2
24          CR2
25          CR2
26          CR2
27          CR2
28          CR2
29          CR2
...         ...
67633       SF3
67634       SF3
67635       SF3
67636       SF3
67637       SF3
67638       SF3
67639       SF3
67640       SF3
67641       SF3
67642       SF3
67643       SF3
67644       SF3
67645       SF3
67646       SF3
67647       SF3
67648       SF3
67649       SF3
67650       SF3
67651       SF3
67652       SF3
67653       SF3
67654       SF3
67655       SF3
67656       SF3
67657       SF3
67658       SF3
67659       734
67660       734
67661       734
67662       734

[67663 rows x 9 columns]

In [8]:
print(routes.columns)

Index(['airline', 'airline_id', 'source', 'source_id', 'dest', 'dest_id',
       'codeshare', 'stops', 'equipment'],
      dtype='object')

2) Select just the routes that go to or from Lexington Bluegrass Airport, and store them in their own dataframe.  

The airport code is LEX.  You should have a much smaller dataframe.  How many inbound routes and how many outbound routes are there?

In [9]:
routes1=routes[routes['source']=='LEX']
routes1

,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment
3588,9E,3976.0,LEX,4017.0,ATL,3682.0,NaN,0,CRJ
5763,AA,24.0,LEX,4017.0,CLT,3876.0,Y,0,CR7 CRJ
5764,AA,24.0,LEX,4017.0,DFW,3670.0,Y,0,ERD ER4
5765,AA,24.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4
9641,AF,137.0,LEX,4017.0,ATL,3682.0,Y,0,CRJ CR9
21095,DL,2009.0,LEX,4017.0,ATL,3682.0,NaN,0,M88 717
21096,DL,2009.0,LEX,4017.0,DCA,3520.0,Y,0,CRJ
21097,DL,2009.0,LEX,4017.0,DTW,3645.0,Y,0,CR7 CRJ CR9
21098,DL,2009.0,LEX,4017.0,LGA,3697.0,NaN,0,ERJ
21099,DL,2009.0,LEX,4017.0,MSP,3858.0,Y,0,CRJ
29047,G4,35.0,LEX,4017.0,FLL,3533.0,NaN,0,M80
29048,G4,35.0,LEX,4017.0,PGD,7056.0,NaN,0,M80
29049,G4,35.0,LEX,4017.0,PIE,3617.0,NaN,0,320
29050,G4,35.0,LEX,4017.0,SFB,4167.0,NaN,0,M80 320
36746,KL,3090.0,LEX,4017.0,ATL,3682.0,Y,0,CR9 CRJ
57029,UA,5209.0,LEX,4017.0,IAH,3550.0,Y,0,ERJ
57030,UA,5209.0,LEX,4017.0,ORD,3830.0,Y,0,ERJ CRJ
59544,US,5265.0,LEX,4017.0,CLT,3876.0,NaN,0,CR7
59545,US,5265.0,LEX,4017.0,DFW,3670.0,NaN,0,ERD
59546,US,5265.0,LEX,4017.0,ORD,3830.0,Y,0,ERD ER4

In [10]:
routes2=routes[routes['dest']=='LEX']
routes2

,airline,airline_id,source,source_id,dest,dest_id,codeshare,stops,equipment
3569,9E,3976.0,ATL,3682.0,LEX,4017.0,NaN,0,CRJ
4953,AA,24.0,CLT,3876.0,LEX,4017.0,NaN,0,CR7
5247,AA,24.0,DFW,3670.0,LEX,4017.0,Y,0,ERD ER4
6283,AA,24.0,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4
9097,AF,137.0,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ 717
20164,DL,2009.0,ATL,3682.0,LEX,4017.0,NaN,0,M88 717
20534,DL,2009.0,DCA,3520.0,LEX,4017.0,Y,0,CRJ
20638,DL,2009.0,DTW,3645.0,LEX,4017.0,NaN,0,717
21131,DL,2009.0,LGA,3697.0,LEX,4017.0,Y,0,ERJ
21402,DL,2009.0,MSP,3858.0,LEX,4017.0,Y,0,CRJ
28951,G4,35.0,FLL,3533.0,LEX,4017.0,NaN,0,M80
29090,G4,35.0,PGD,7056.0,LEX,4017.0,NaN,0,M80
29120,G4,35.0,PIE,3617.0,LEX,4017.0,NaN,0,320
29187,G4,35.0,SFB,4167.0,LEX,4017.0,NaN,0,M80 320
36396,KL,3090.0,ATL,3682.0,LEX,4017.0,Y,0,CR9 M88 CRJ
56775,UA,5209.0,IAH,3550.0,LEX,4017.0,Y,0,ERJ
57322,UA,5209.0,ORD,3830.0,LEX,4017.0,Y,0,ERJ CRJ
58812,US,5265.0,CLT,3876.0,LEX,4017.0,NaN,0,CR7
59096,US,5265.0,DFW,3670.0,LEX,4017.0,NaN,0,ERD
59924,US,5265.0,ORD,3830.0,LEX,4017.0,Y,0,ERD ER4

3) Now let's look at which airlines operate in and out of Lexington.  To do this, you need to merge the airline dataframe to the route dataframe.  

How many routes does each airline have?  The value_counts() method may be useful for answering this question.

In [33]:
merge1 = pd.merge(airlines, routes1, on='id',  how='right')
merge1

,id,name_x,alias,iata_x,icao_x,callsign,country_x,active,airline,airline_id,...,iata_y,icao_y,latitude,longitude,altitude,timezone,dst,tz,type,source_y
0,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,9E,3976.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
1,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,AA,24.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
2,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,AA,24.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
3,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,AA,24.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
4,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,AF,137.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
5,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
6,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
7,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
8,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
9,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
10,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,G4,35.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
11,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,G4,35.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
12,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,G4,35.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
13,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,G4,35.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
14,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,KL,3090.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
15,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,UA,5209.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
16,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,UA,5209.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
17,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,US,5265.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
18,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,US,5265.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports
19,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,US,5265.0,...,LEX,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports

In [38]:
routes2 = pd.merge(routes2 , airports, left_on='source_id', right_on='id', how='left')

In [39]:
merge2 = pd.merge(airlines, routes2, on='id',  how='right')
merge2

,id,name_x,alias,iata_x,icao_x,callsign,country_x,active,airline,airline_id,...,iata_y,icao_y,latitude,longitude,altitude,timezone,dst,tz,type,source_y
0,3520.0,Missionair,NaN,NaN,MSN,MISIONAIR,Spain,N,DL,2009.0,...,DCA,KDCA,38.852100,-77.037697,15,-5.0,A,America/New_York,airport,OurAirports
1,3533.0,Monarch Airlines,NaN,NaN,MNH,MONARCH AIR,United States,N,G4,35.0,...,FLL,KFLL,26.072599,-80.152702,9,-5.0,A,America/New_York,airport,OurAirports
2,3550.0,Mountain Air Company,NaN,N4,MTC,MOUNTAIN LEONE,Sierra Leone,N,UA,5209.0,...,IAH,KIAH,29.984400,-95.341400,97,-6.0,A,America/Chicago,airport,OurAirports
3,3617.0,Naturelink Charter,NaN,NaN,NRK,NATURELINK,South Africa,N,G4,35.0,...,PIE,KPIE,27.910200,-82.687401,11,-5.0,A,America/New_York,airport,OurAirports
4,3645.0,New Heights 291,NaN,NaN,NHT,NEWHEIGHTS,South Africa,N,DL,2009.0,...,DTW,KDTW,42.212399,-83.353401,645,-5.0,A,America/New_York,airport,OurAirports
5,3670.0,Search and Rescue 22,NaN,NaN,SRD,NaN,United Kingdom,N,AA,24.0,...,DFW,KDFW,32.896801,-97.038002,607,-6.0,A,America/Chicago,airport,OurAirports
6,3670.0,Search and Rescue 22,NaN,NaN,SRD,NaN,United Kingdom,N,US,5265.0,...,DFW,KDFW,32.896801,-97.038002,607,-6.0,A,America/Chicago,airport,OurAirports
7,3682.0,Nordstree (Australia),NaN,NaN,NDS,NaN,Australia,N,9E,3976.0,...,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports
8,3682.0,Nordstree (Australia),NaN,NaN,NDS,NaN,Australia,N,AF,137.0,...,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports
9,3682.0,Nordstree (Australia),NaN,NaN,NDS,NaN,Australia,N,DL,2009.0,...,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports
10,3682.0,Nordstree (Australia),NaN,NaN,NDS,NaN,Australia,N,KL,3090.0,...,ATL,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports
11,3697.0,North Atlantic Cargo,NaN,NaN,NFC,NORTH ATLANTIC,Norway,N,DL,2009.0,...,LGA,KLGA,40.777199,-73.872597,21,-5.0,A,America/New_York,airport,OurAirports
12,3830.0,Ozark Air Lines,NaN,OZ,OZR,OZARK,United States,N,AA,24.0,...,ORD,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports
13,3830.0,Ozark Air Lines,NaN,OZ,OZR,OZARK,United States,N,UA,5209.0,...,ORD,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports
14,3830.0,Ozark Air Lines,NaN,OZ,OZR,OZARK,United States,N,US,5265.0,...,ORD,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports
15,3858.0,Pacific Flight Services,NaN,NaN,PFA,PACIFIC SING,Singapore,N,DL,2009.0,...,MSP,KMSP,44.882000,-93.221802,841,-6.0,A,America/Chicago,airport,OurAirports
16,3876.0,Palestinian Airlines,NaN,PF,PNW,PALESTINIAN,Egypt,N,AA,24.0,...,CLT,KCLT,35.214001,-80.943100,748,-5.0,A,America/New_York,airport,OurAirports
17,3876.0,Palestinian Airlines,NaN,PF,PNW,PALESTINIAN,Egypt,N,US,5265.0,...,CLT,KCLT,35.214001,-80.943100,748,-5.0,A,America/New_York,airport,OurAirports
18,4167.0,Regal Bahamas International Airways,NaN,NaN,RBH,CALYPSO,Bahamas,N,G4,35.0,...,SFB,KSFB,28.777599,-81.237503,55,-5.0,A,America/New_York,airport,OurAirports
19,7056.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G4,35.0,...,PGD,KPGD,26.920200,-81.990501,26,-5.0,A,America/New_York,airport,OurAirports

4) It looks like there are some international airlines with Lexington routes.  To look at how many routes they have, create a new column in your dataframe called 'International', which is set to Y for an overseas airline and N for a domestic airline.  Calculate the percent of routes with an overseas airline.

In [41]:
merge1['International']=np.where(merge1['country_x']=='United States','N','Y')
merge1

,id,name_x,alias,iata_x,icao_x,callsign,country_x,active,airline,airline_id,...,icao_y,latitude,longitude,altitude,timezone,dst,tz,type,source_y,International
0,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,9E,3976.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
1,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,AA,24.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
2,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,AA,24.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
3,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,AA,24.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
4,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,AF,137.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
5,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
6,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
7,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
8,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
9,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,DL,2009.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
10,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,G4,35.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
11,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,G4,35.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
12,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,G4,35.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
13,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,G4,35.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
14,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,KL,3090.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
15,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,UA,5209.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
16,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,UA,5209.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
17,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,US,5265.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
18,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,US,5265.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y
19,4017,Pont International Airline Services,NaN,NaN,PSI,PONT,Suriname,N,US,5265.0,...,KLEX,38.036499,-84.605904,979,-5.0,A,America/New_York,airport,OurAirports,Y

In [42]:
merge2['International']=np.where(merge2['country_x']=='United States','N','Y')
merge2

,id,name_x,alias,iata_x,icao_x,callsign,country_x,active,airline,airline_id,...,icao_y,latitude,longitude,altitude,timezone,dst,tz,type,source_y,International
0,3520.0,Missionair,NaN,NaN,MSN,MISIONAIR,Spain,N,DL,2009.0,...,KDCA,38.852100,-77.037697,15,-5.0,A,America/New_York,airport,OurAirports,Y
1,3533.0,Monarch Airlines,NaN,NaN,MNH,MONARCH AIR,United States,N,G4,35.0,...,KFLL,26.072599,-80.152702,9,-5.0,A,America/New_York,airport,OurAirports,N
2,3550.0,Mountain Air Company,NaN,N4,MTC,MOUNTAIN LEONE,Sierra Leone,N,UA,5209.0,...,KIAH,29.984400,-95.341400,97,-6.0,A,America/Chicago,airport,OurAirports,Y
3,3617.0,Naturelink Charter,NaN,NaN,NRK,NATURELINK,South Africa,N,G4,35.0,...,KPIE,27.910200,-82.687401,11,-5.0,A,America/New_York,airport,OurAirports,Y
4,3645.0,New Heights 291,NaN,NaN,NHT,NEWHEIGHTS,South Africa,N,DL,2009.0,...,KDTW,42.212399,-83.353401,645,-5.0,A,America/New_York,airport,OurAirports,Y
5,3670.0,Search and Rescue 22,NaN,NaN,SRD,NaN,United Kingdom,N,AA,24.0,...,KDFW,32.896801,-97.038002,607,-6.0,A,America/Chicago,airport,OurAirports,Y
6,3670.0,Search and Rescue 22,NaN,NaN,SRD,NaN,United Kingdom,N,US,5265.0,...,KDFW,32.896801,-97.038002,607,-6.0,A,America/Chicago,airport,OurAirports,Y
7,3682.0,Nordstree (Australia),NaN,NaN,NDS,NaN,Australia,N,9E,3976.0,...,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports,Y
8,3682.0,Nordstree (Australia),NaN,NaN,NDS,NaN,Australia,N,AF,137.0,...,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports,Y
9,3682.0,Nordstree (Australia),NaN,NaN,NDS,NaN,Australia,N,DL,2009.0,...,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports,Y
10,3682.0,Nordstree (Australia),NaN,NaN,NDS,NaN,Australia,N,KL,3090.0,...,KATL,33.636700,-84.428101,1026,-5.0,A,America/New_York,airport,OurAirports,Y
11,3697.0,North Atlantic Cargo,NaN,NaN,NFC,NORTH ATLANTIC,Norway,N,DL,2009.0,...,KLGA,40.777199,-73.872597,21,-5.0,A,America/New_York,airport,OurAirports,Y
12,3830.0,Ozark Air Lines,NaN,OZ,OZR,OZARK,United States,N,AA,24.0,...,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports,N
13,3830.0,Ozark Air Lines,NaN,OZ,OZR,OZARK,United States,N,UA,5209.0,...,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports,N
14,3830.0,Ozark Air Lines,NaN,OZ,OZR,OZARK,United States,N,US,5265.0,...,KORD,41.978600,-87.904800,672,-6.0,A,America/Chicago,airport,OurAirports,N
15,3858.0,Pacific Flight Services,NaN,NaN,PFA,PACIFIC SING,Singapore,N,DL,2009.0,...,KMSP,44.882000,-93.221802,841,-6.0,A,America/Chicago,airport,OurAirports,Y
16,3876.0,Palestinian Airlines,NaN,PF,PNW,PALESTINIAN,Egypt,N,AA,24.0,...,KCLT,35.214001,-80.943100,748,-5.0,A,America/New_York,airport,OurAirports,Y
17,3876.0,Palestinian Airlines,NaN,PF,PNW,PALESTINIAN,Egypt,N,US,5265.0,...,KCLT,35.214001,-80.943100,748,-5.0,A,America/New_York,airport,OurAirports,Y
18,4167.0,Regal Bahamas International Airways,NaN,NaN,RBH,CALYPSO,Bahamas,N,G4,35.0,...,KSFB,28.777599,-81.237503,55,-5.0,A,America/New_York,airport,OurAirports,Y
19,7056.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G4,35.0,...,KPGD,26.920200,-81.990501,26,-5.0,A,America/New_York,airport,OurAirports,Y

5) Actually, it looks like a bunch of these routes are codeshares.  That means they are marketed by this airline, but operated by a different airline.  See the note in the data documentation on openflights.org/data.  The implication of this is that there are duplicates.

Can you figure out which ones are duplicates?  Can you then create a dataframe with only the unique routes?  How many unique inbound and outbound routes are there? 

Remember, someone has to operate the flight, so if all the routes to/from a particular airport are listed as codeshares, then something is funny...

It is also possible that more than one airline actually operates a route between the same two airports. (Having this sort of competition generally means that you will get better fares as a traveler.)  It may not be obvious what is actually in the data set, so dig or do external research as needed.